import { Assets } from 'pixi.js';
import { SOUND_CUES, type AudioOutput, type SoundCue } from './Sound';

/** Generated by `npm run assets:audio`, served from `public/`. */
export const SOUND_FILES: Readonly<Record<SoundCue, string>> = {
  click: 'ui/click.wav',
  step: 'game/step.wav',
  crash: 'game/crash.wav',
  cashOut: 'game/cashout.wav',
  finish: 'game/finish.wav',
};

export const soundUrl = (cue: SoundCue) =>
  `${import.meta.env.BASE_URL}assets/audio/${SOUND_FILES[cue]}`;
export const soundAlias = (cue: SoundCue) => `sound-${cue}`;

let loading: Promise<AudioOutput | null> | null = null;

/**
 * Loads every clip once and shares the result. Sound is optional: a clip that fails is left
 * out with a warning, and if the audio library itself is unavailable the result is null.
 * The promise never rejects, so audio can never hold up the game.
 */
export function loadGameAudio(): Promise<AudioOutput | null> {
  loading ??= load();
  return loading;
}

async function load(): Promise<AudioOutput | null> {
  let library: typeof import('@pixi/sound');
  try {
    // Kept out of the main bundle; importing it also registers the sound loader with Assets.
    library = await import('@pixi/sound');
  } catch (error) {
    console.warn('Audio is unavailable, the game continues without sound', error);
    return null;
  }

  const results = await Promise.allSettled(
    SOUND_CUES.map(async (cue) => {
      const alias = soundAlias(cue);
      if (!Assets.resolver.hasKey(alias)) Assets.add({ alias, src: soundUrl(cue) });
      await Assets.load(alias);
      return cue;
    }),
  );
  const cues = new Set<SoundCue>();
  results.forEach((result, i) => {
    const cue = SOUND_CUES[i] as SoundCue;
    if (result.status === 'fulfilled') cues.add(cue);
    else console.warn(`Could not load sound "${cue}" from ${soundUrl(cue)}`, result.reason);
  });
  if (cues.size === 0) return null;

  const { sound } = library;
  return {
    cues,
    play: (cue, volume) => void sound.play(soundAlias(cue), { volume }),
    stopAll: () => void sound.stopAll(),
    unlock: () => {
      const context = sound.useLegacy ? null : sound.context.audioContext;
      if (context && context.state !== 'running') {
        context.resume().catch((error: unknown) => {
          console.warn('The browser did not allow audio to start yet', error);
        });
      }
    },
  };
}
